project:
  type: website
  output-dir: docs
  
website:
  title: "Gerry's test site"
  navbar:
    logo: "logo.png"
    left:
      - href: closeread_test.qmd
        text: Closeread
      - href: gallery_test.qmd
        text: "Photo gallery"